version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: music-metadata
    versions:
    - 7.6.5
    - 7.6.6
    - 7.6.7
    - 7.6.8
    - 7.7.0
    - 7.8.0
    - 7.8.1
    - 7.8.3
    - 7.8.4
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@vue/cli-plugin-typescript"
    versions:
    - 4.5.11
