export const READ_MUSIC_FOLDER = "READ_MUSIC_FOLDER";
export const ADD_TO_QUEUE = "ADD_TO_QUEUE";
// PLAYER ACTIONS
export const PLAY_SONG = "PLAY_SONG";
export const PLAY_NEXT_SONG = "PLAY_NEXT_SONG";
export const PLAY_PREV_SONG = "PLAY_PREV_SONG";
export const PLAY_RANDOM_SONG = "PLAY_RANDOM_SONG";
// PLAYLIST ACTIONS
export const NEW_PLAYLIST = "NEW_PLAYLIST";
export const RENAME_PLAYLIST = "RENAME_PLAYLIST";
export const ADD_TO_PLAYLIST = "ADD_TO_PLAYLIST";
export const DELETE_PLAYLIST = "DELETE_PLAYLIST";
export const REMOVE_SONG_FROM_PLAYLIST = "REMOVE_SONG_FROM_PLAYLIST";
// NOTIFICATIONS ACTIONS
export const NEW_SONG_NOTIF = "NEW_SONG_NOTIF";
